apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alpine:latest
    command: ["sh", "-c", "echo hello-from-kubectl"]
