//! Application state and update logic.

use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};
use std::collections::HashSet;
use std::sync::{mpsc, Arc, Mutex};
use std::time::Instant;

use crate::runner::Container;

// ---------------------------------------------------------------------------
// Subscription message (deserialized from `pelagos subscribe` NDJSON output)
// ---------------------------------------------------------------------------

/// Wire-format events from `pelagos subscribe`.  Must match `GuestEvent` in
/// pelagos-guest exactly (same `#[serde(tag = "type", rename_all = "snake_case")]`).
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SubscriptionMsg {
    Snapshot {
        containers: Vec<Container>,
        vm_running: bool,
    },
    ContainerStarted {
        container: Container,
    },
    ContainerExited {
        name: String,
        #[allow(dead_code)]
        exit_code: Option<i32>,
    },
    /// Periodic liveness ping from the guest (~5s interval).
    Heartbeat {
        #[allow(dead_code)]
        ts: u64,
    },
    /// Synthetic event generated by the subscription thread on disconnect.
    #[serde(skip)]
    Disconnected,
}

// ---------------------------------------------------------------------------
// ConfirmAction
// ---------------------------------------------------------------------------

/// The action being confirmed in `Mode::Confirm`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ConfirmAction {
    Stop,
    Restart,
    Remove,
    /// Stop then remove: used when at least one target is currently running.
    StopAndRemove,
}

impl ConfirmAction {
    /// Human-readable verb used in the confirmation prompt.
    pub fn verb(&self) -> &'static str {
        match self {
            ConfirmAction::Stop => "stop",
            ConfirmAction::Restart => "restart",
            ConfirmAction::Remove => "remove",
            ConfirmAction::StopAndRemove => "stop and remove",
        }
    }

    /// The `pelagos` subcommand name.  `StopAndRemove` is handled specially in
    /// `execute_action_bg` and should not be used directly as a subcommand.
    pub fn pelagos_cmd(&self) -> &'static str {
        match self {
            ConfirmAction::Stop => "stop",
            ConfirmAction::Restart => "restart",
            ConfirmAction::Remove => "rm",
            ConfirmAction::StopAndRemove => "rm",
        }
    }
}

// ---------------------------------------------------------------------------
// Mode
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Mode {
    Normal,
    ProfilePicker,
    /// Command palette: modeline becomes a `run> <input>` text field.
    CommandPalette,
    /// Waiting for y/N confirmation before executing an action on containers.
    Confirm,
    /// Waiting for y/N/q confirmation before quitting.
    ConfirmQuit,
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

pub struct App {
    pub mode: Mode,
    pub containers: Vec<Container>,
    /// Index of the highlighted row in Normal mode.
    pub selected: usize,
    /// Names of rows with Space-toggled multi-select (order preserved via containers list).
    pub selected_names: HashSet<String>,
    pub show_all: bool,
    pub profile: String,
    pub profiles: Vec<String>,
    pub vm_running: bool,
    pub last_refresh: Instant,
    pub profile_picker_selected: usize,
    pub should_quit: bool,
    pub palette_input: String,
    /// Set by the palette on Enter; main.rs drains this to spawn the run.
    pub pending_run: Option<String>,
    /// Set by confirm on 'y'; main.rs drains this to execute the action.
    pub pending_action: Option<(ConfirmAction, Vec<String>)>,
    pub status_message: Option<String>,
    pub status_tx: Option<mpsc::SyncSender<String>>,
    pub status_rx: Option<mpsc::Receiver<String>>,
    pub subscription_reconnecting: bool,
    pub sub_config: Option<Arc<Mutex<crate::SubConfig>>>,
    pub last_any_msg: Instant,
    // Confirm mode state — valid only when mode == Mode::Confirm.
    pub confirm_action: Option<ConfirmAction>,
    pub confirm_targets: Vec<String>,
}

impl App {
    pub fn new(profile: String, profiles: Vec<String>) -> Self {
        let picker_idx = profiles.iter().position(|p| p == &profile).unwrap_or(0);
        let (status_tx, status_rx) = mpsc::sync_channel(8);
        Self {
            mode: Mode::Normal,
            containers: Vec::new(),
            selected: 0,
            selected_names: HashSet::new(),
            show_all: false,
            profile,
            profiles,
            vm_running: false,
            last_refresh: Instant::now(),
            profile_picker_selected: picker_idx,
            should_quit: false,
            palette_input: String::new(),
            pending_run: None,
            pending_action: None,
            status_message: None,
            status_tx: Some(status_tx),
            status_rx: Some(status_rx),
            subscription_reconnecting: false,
            sub_config: None,
            last_any_msg: Instant::now(),
            confirm_action: None,
            confirm_targets: Vec::new(),
        }
    }

    // -----------------------------------------------------------------------
    // Subscription event application
    // -----------------------------------------------------------------------

    pub fn apply_subscription(&mut self, msg: SubscriptionMsg) {
        if let Some(rx) = &self.status_rx {
            while let Ok(msg) = rx.try_recv() {
                self.status_message = Some(msg);
            }
        }
        self.last_any_msg = Instant::now();

        match msg {
            SubscriptionMsg::Snapshot {
                containers,
                vm_running,
            } => {
                self.containers = if self.show_all {
                    containers
                } else {
                    containers
                        .into_iter()
                        .filter(|c| c.status == "running")
                        .collect()
                };
                // Drop selections for containers no longer present.
                let present: HashSet<String> =
                    self.containers.iter().map(|c| c.name.clone()).collect();
                self.selected_names.retain(|n| present.contains(n));
                clamp_selected(&mut self.selected, self.containers.len());
                self.vm_running = vm_running;
                self.last_refresh = Instant::now();
                self.subscription_reconnecting = false;
                self.status_message = None;
            }

            SubscriptionMsg::ContainerStarted { container } => {
                if self.show_all || container.status == "running" {
                    if let Some(pos) = self
                        .containers
                        .iter()
                        .position(|c| c.name == container.name)
                    {
                        self.containers[pos] = container;
                    } else {
                        self.containers.push(container);
                    }
                }
                self.last_refresh = Instant::now();
            }

            SubscriptionMsg::ContainerExited { name, .. } => {
                if !self.show_all {
                    self.containers.retain(|c| c.name != name);
                    self.selected_names.remove(&name);
                    clamp_selected(&mut self.selected, self.containers.len());
                } else if let Some(c) = self.containers.iter_mut().find(|c| c.name == name) {
                    c.status = "exited".to_string();
                }
                self.last_refresh = Instant::now();
            }

            SubscriptionMsg::Heartbeat { .. } => {
                self.last_refresh = Instant::now();
            }

            SubscriptionMsg::Disconnected => {
                self.vm_running = false;
                self.subscription_reconnecting = true;
            }
        }
    }

    pub fn subscription_stale(&self) -> bool {
        !self.subscription_reconnecting && self.last_any_msg.elapsed().as_secs() > 15
    }

    // -----------------------------------------------------------------------
    // Key handling
    // -----------------------------------------------------------------------

    pub fn on_key(&mut self, key: KeyEvent) {
        match self.mode {
            Mode::Normal => self.on_key_normal(key),
            Mode::ProfilePicker => self.on_key_profile_picker(key),
            Mode::CommandPalette => self.on_key_palette(key),
            Mode::Confirm => self.on_key_confirm(key),
            Mode::ConfirmQuit => self.on_key_confirm_quit(key),
        }
    }

    fn on_key_normal(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Char('q') => self.mode = Mode::ConfirmQuit,
            KeyCode::Char('c') if key.modifiers.contains(KeyModifiers::CONTROL) => {
                self.should_quit = true;
            }

            KeyCode::Char('j') | KeyCode::Down => {
                if !self.containers.is_empty() {
                    self.selected = (self.selected + 1).min(self.containers.len() - 1);
                }
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.selected = self.selected.saturating_sub(1);
            }

            // Space: toggle multi-select on highlighted row, then advance cursor.
            KeyCode::Char(' ') => {
                if let Some(c) = self.containers.get(self.selected) {
                    let name = c.name.clone();
                    if !self.selected_names.remove(&name) {
                        self.selected_names.insert(name);
                    }
                    if self.selected + 1 < self.containers.len() {
                        self.selected += 1;
                    }
                }
            }

            KeyCode::Char('a') => {
                self.show_all = !self.show_all;
                self.selected = 0;
                self.selected_names.clear();
                if let Some(cfg) = &self.sub_config {
                    let mut c = cfg.lock().unwrap();
                    c.generation = c.generation.wrapping_add(1);
                }
            }

            KeyCode::Char('p') => {
                self.profile_picker_selected = self
                    .profiles
                    .iter()
                    .position(|p| p == &self.profile)
                    .unwrap_or(0);
                self.mode = Mode::ProfilePicker;
            }

            KeyCode::Char('r') => {
                self.palette_input.clear();
                self.mode = Mode::CommandPalette;
            }

            // Container actions — operate on multi-selection or highlighted row.
            KeyCode::Char('s') => self.begin_action(ConfirmAction::Stop),
            KeyCode::Char('S') => self.begin_action(ConfirmAction::Restart),
            KeyCode::Char('d') => self.begin_action(ConfirmAction::Remove),

            // Prune: target all exited containers regardless of selection.
            KeyCode::Char('P') => {
                let targets: Vec<String> = self
                    .containers
                    .iter()
                    .filter(|c| c.status != "running")
                    .map(|c| c.name.clone())
                    .collect();
                if targets.is_empty() {
                    self.status_message = Some("no exited containers to prune".to_string());
                } else {
                    self.confirm_action = Some(ConfirmAction::Remove);
                    self.confirm_targets = targets;
                    self.mode = Mode::Confirm;
                }
            }

            _ => {}
        }
    }

    fn on_key_profile_picker(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Char('j') | KeyCode::Down => {
                if !self.profiles.is_empty() {
                    self.profile_picker_selected =
                        (self.profile_picker_selected + 1).min(self.profiles.len() - 1);
                }
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.profile_picker_selected = self.profile_picker_selected.saturating_sub(1);
            }
            KeyCode::Enter => {
                if let Some(chosen) = self.profiles.get(self.profile_picker_selected).cloned() {
                    if chosen != self.profile {
                        log::debug!("profile switch: {} -> {}", self.profile, chosen);
                        self.profile = chosen.clone();
                        self.containers.clear();
                        self.selected = 0;
                        self.selected_names.clear();
                        if let Some(cfg) = &self.sub_config {
                            let mut c = cfg.lock().unwrap();
                            c.profile = chosen;
                            c.generation = c.generation.wrapping_add(1);
                        }
                    }
                }
                self.mode = Mode::Normal;
            }
            KeyCode::Esc | KeyCode::Char('p') => {
                self.mode = Mode::Normal;
            }
            _ => {}
        }
    }

    fn on_key_palette(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Esc => {
                self.palette_input.clear();
                self.mode = Mode::Normal;
            }
            KeyCode::Enter => {
                let input = self.palette_input.trim().to_string();
                if !input.is_empty() {
                    self.pending_run = Some(input);
                }
                self.palette_input.clear();
                self.mode = Mode::Normal;
            }
            KeyCode::Backspace => {
                self.palette_input.pop();
            }
            KeyCode::Char(c) => {
                self.palette_input.push(c);
            }
            _ => {}
        }
    }

    fn on_key_confirm(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Char('y') | KeyCode::Char('Y') => {
                if let Some(action) = self.confirm_action.take() {
                    let targets = std::mem::take(&mut self.confirm_targets);
                    self.pending_action = Some((action, targets));
                }
                self.selected_names.clear();
                self.mode = Mode::Normal;
            }
            _ => {
                // Any key other than 'y' cancels.
                self.confirm_action = None;
                self.confirm_targets.clear();
                self.mode = Mode::Normal;
            }
        }
    }

    fn on_key_confirm_quit(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Char('y') | KeyCode::Char('Y') | KeyCode::Char('q') => {
                self.should_quit = true;
            }
            _ => {
                self.mode = Mode::Normal;
            }
        }
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /// Returns target names for an action: the multi-selection (in list order)
    /// if non-empty, otherwise the single highlighted container.
    fn action_targets(&self) -> Vec<String> {
        if !self.selected_names.is_empty() {
            self.containers
                .iter()
                .filter(|c| self.selected_names.contains(&c.name))
                .map(|c| c.name.clone())
                .collect()
        } else {
            self.containers
                .get(self.selected)
                .map(|c| vec![c.name.clone()])
                .unwrap_or_default()
        }
    }

    fn begin_action(&mut self, action: ConfirmAction) {
        let targets = self.action_targets();
        if targets.is_empty() {
            return;
        }
        // If the user asks to remove a container that is still running, upgrade
        // to StopAndRemove so they get a clear prompt and the stop happens first.
        let action = if action == ConfirmAction::Remove {
            let any_running = self
                .containers
                .iter()
                .filter(|c| targets.contains(&c.name))
                .any(|c| c.status == "running");
            if any_running {
                ConfirmAction::StopAndRemove
            } else {
                action
            }
        } else {
            action
        };
        self.confirm_action = Some(action);
        self.confirm_targets = targets;
        self.mode = Mode::Confirm;
    }

    #[allow(dead_code)]
    pub fn selected_container(&self) -> Option<&Container> {
        self.containers.get(self.selected)
    }

    pub fn refresh_age_secs(&self) -> u64 {
        self.last_refresh.elapsed().as_secs()
    }
}

fn clamp_selected(selected: &mut usize, len: usize) {
    if len == 0 {
        *selected = 0;
    } else if *selected >= len {
        *selected = len - 1;
    }
}
