//! Application state and update logic.

use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};
use std::sync::{mpsc, Arc, Mutex};
use std::time::Instant;

use crate::runner::Container;

// ---------------------------------------------------------------------------
// Subscription message (deserialized from `pelagos subscribe` NDJSON output)
// ---------------------------------------------------------------------------

/// Wire-format events from `pelagos subscribe`.  Must match `GuestEvent` in
/// pelagos-guest exactly (same `#[serde(tag = "type", rename_all = "snake_case")]`).
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SubscriptionMsg {
    /// Initial snapshot sent by the guest on connect.
    Snapshot {
        containers: Vec<Container>,
        vm_running: bool,
    },
    /// A container became running.
    ContainerStarted { container: Container },
    /// A container exited or was removed.
    ContainerExited {
        name: String,
        #[allow(dead_code)]
        exit_code: Option<i32>,
    },
    /// Synthetic event generated by the subscription thread on disconnect.
    #[serde(skip)]
    Disconnected,
}

// ---------------------------------------------------------------------------
// Mode
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Mode {
    Normal,
    ProfilePicker,
    /// Command palette: modeline becomes a `run> <input>` text field.
    CommandPalette,
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

pub struct App {
    pub mode: Mode,
    pub containers: Vec<Container>,
    /// Index of the highlighted row in Normal mode.
    pub selected: usize,
    /// Whether to show all containers (including stopped).
    pub show_all: bool,
    /// Currently active profile name.
    pub profile: String,
    /// All known profiles (populated at startup and on profile change).
    pub profiles: Vec<String>,
    /// Whether the VM daemon is running (last known state from subscription).
    pub vm_running: bool,
    /// When we last received any subscription message (for modeline age display).
    pub last_refresh: Instant,
    /// Highlighted row index inside the profile picker overlay.
    pub profile_picker_selected: usize,
    /// Set to true to break the event loop.
    pub should_quit: bool,
    /// Text being typed in the command palette.
    pub palette_input: String,
    /// Set by the palette on Enter; main.rs drains this to spawn the run.
    pub pending_run: Option<String>,
    /// Transient error/status shown in the modeline (cleared on next snapshot).
    pub status_message: Option<String>,
    /// Channel used by background run threads to report errors back to the UI.
    /// Stored here so main.rs can clone the sender for each spawned thread.
    pub status_tx: Option<mpsc::SyncSender<String>>,
    /// Receiver for status messages from background threads.
    pub status_rx: Option<mpsc::Receiver<String>>,
    /// True while waiting for a subscription reconnect.
    pub subscription_reconnecting: bool,
    /// Shared config for the subscription thread (profile + generation counter).
    pub sub_config: Option<Arc<Mutex<crate::SubConfig>>>,
}

impl App {
    pub fn new(profile: String, profiles: Vec<String>) -> Self {
        let picker_idx = profiles.iter().position(|p| p == &profile).unwrap_or(0);

        let (status_tx, status_rx) = mpsc::sync_channel(8);

        Self {
            mode: Mode::Normal,
            containers: Vec::new(),
            selected: 0,
            show_all: false,
            profile,
            profiles,
            vm_running: false,
            last_refresh: Instant::now(),
            profile_picker_selected: picker_idx,
            should_quit: false,
            palette_input: String::new(),
            pending_run: None,
            status_message: None,
            status_tx: Some(status_tx),
            status_rx: Some(status_rx),
            subscription_reconnecting: false,
            sub_config: None,
        }
    }

    // -----------------------------------------------------------------------
    // Subscription event application
    // -----------------------------------------------------------------------

    pub fn apply_subscription(&mut self, msg: SubscriptionMsg) {
        // Drain any status messages from background run threads first.
        if let Some(rx) = &self.status_rx {
            while let Ok(msg) = rx.try_recv() {
                self.status_message = Some(msg);
            }
        }

        match msg {
            SubscriptionMsg::Snapshot {
                containers,
                vm_running,
            } => {
                // Filter according to show_all if the guest doesn't.
                self.containers = if self.show_all {
                    containers
                } else {
                    containers
                        .into_iter()
                        .filter(|c| c.status == "running")
                        .collect()
                };
                clamp_selected(&mut self.selected, self.containers.len());
                self.vm_running = vm_running;
                self.last_refresh = Instant::now();
                self.subscription_reconnecting = false;
                self.status_message = None;
            }

            SubscriptionMsg::ContainerStarted { container } => {
                if self.show_all || container.status == "running" {
                    if let Some(pos) = self
                        .containers
                        .iter()
                        .position(|c| c.name == container.name)
                    {
                        self.containers[pos] = container;
                    } else {
                        self.containers.push(container);
                    }
                }
                self.last_refresh = Instant::now();
            }

            SubscriptionMsg::ContainerExited { name, .. } => {
                if !self.show_all {
                    self.containers.retain(|c| c.name != name);
                    clamp_selected(&mut self.selected, self.containers.len());
                } else if let Some(c) = self.containers.iter_mut().find(|c| c.name == name) {
                    c.status = "exited".to_string();
                }
                self.last_refresh = Instant::now();
            }

            SubscriptionMsg::Disconnected => {
                self.vm_running = false;
                self.subscription_reconnecting = true;
            }
        }
    }

    // -----------------------------------------------------------------------
    // Key handling (no longer needs Runner — runs trigger background threads)
    // -----------------------------------------------------------------------

    pub fn on_key(&mut self, key: KeyEvent) {
        match self.mode {
            Mode::Normal => self.on_key_normal(key),
            Mode::ProfilePicker => self.on_key_profile_picker(key),
            Mode::CommandPalette => self.on_key_palette(key),
        }
    }

    fn on_key_normal(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Char('q') => {
                self.should_quit = true;
            }
            KeyCode::Char('c') if key.modifiers.contains(KeyModifiers::CONTROL) => {
                self.should_quit = true;
            }

            KeyCode::Char('j') | KeyCode::Down => {
                if !self.containers.is_empty() {
                    self.selected = (self.selected + 1).min(self.containers.len() - 1);
                }
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.selected = self.selected.saturating_sub(1);
            }

            KeyCode::Char('a') => {
                self.show_all = !self.show_all;
                self.containers.clear();
                self.selected = 0;
                // Force subscription reconnect so the guest sends a fresh snapshot.
                if let Some(cfg) = &self.sub_config {
                    let mut c = cfg.lock().unwrap();
                    c.generation = c.generation.wrapping_add(1);
                }
            }

            KeyCode::Char('p') => {
                self.profile_picker_selected = self
                    .profiles
                    .iter()
                    .position(|p| p == &self.profile)
                    .unwrap_or(0);
                self.mode = Mode::ProfilePicker;
            }

            KeyCode::Char('r') => {
                self.palette_input.clear();
                self.mode = Mode::CommandPalette;
            }

            _ => {}
        }
    }

    fn on_key_profile_picker(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Char('j') | KeyCode::Down => {
                if !self.profiles.is_empty() {
                    self.profile_picker_selected =
                        (self.profile_picker_selected + 1).min(self.profiles.len() - 1);
                }
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.profile_picker_selected = self.profile_picker_selected.saturating_sub(1);
            }

            KeyCode::Enter => {
                if let Some(chosen) = self.profiles.get(self.profile_picker_selected).cloned() {
                    if chosen != self.profile {
                        log::debug!("profile switch: {} -> {}", self.profile, chosen);
                        self.profile = chosen.clone();
                        self.containers.clear();
                        self.selected = 0;
                        // Update sub_config and bump generation to force reconnect.
                        if let Some(cfg) = &self.sub_config {
                            let mut c = cfg.lock().unwrap();
                            c.profile = chosen;
                            c.generation = c.generation.wrapping_add(1);
                        }
                    }
                }
                self.mode = Mode::Normal;
            }

            KeyCode::Esc | KeyCode::Char('p') => {
                self.mode = Mode::Normal;
            }

            _ => {}
        }
    }

    fn on_key_palette(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Esc => {
                self.palette_input.clear();
                self.mode = Mode::Normal;
            }
            KeyCode::Enter => {
                let input = self.palette_input.trim().to_string();
                if !input.is_empty() {
                    self.pending_run = Some(input);
                }
                self.palette_input.clear();
                self.mode = Mode::Normal;
            }
            KeyCode::Backspace => {
                self.palette_input.pop();
            }
            KeyCode::Char(c) => {
                self.palette_input.push(c);
            }
            _ => {}
        }
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    #[allow(dead_code)]
    pub fn selected_container(&self) -> Option<&Container> {
        self.containers.get(self.selected)
    }

    pub fn refresh_age_secs(&self) -> u64 {
        self.last_refresh.elapsed().as_secs()
    }
}

fn clamp_selected(selected: &mut usize, len: usize) {
    if len == 0 {
        *selected = 0;
    } else if *selected >= len {
        *selected = len - 1;
    }
}
