#!/usr/bin/env bash
# build-release.sh — Build local release tarballs and a Homebrew test formula.
#
# Produces two tarballs in dist/ that mirror the production CI layout:
#
#   dist/pelagos-mac-<version>-aarch64-apple-darwin.tar.gz  (~15 MB)
#     pelagos
#     pelagos-docker
#
#   dist/pelagos-mac-vm-<version>.tar.gz  (~215 MB)
#     vmlinuz          (normalised from out/ubuntu-vmlinuz)
#     initramfs.gz     (normalised from out/initramfs-custom.gz)
#     root.img
#
# Also sets up a local Homebrew tap (skeptomai/tap) backed by dist/tap/ so
# you can install without a GitHub release:
#
#   bash scripts/build-release.sh
#   brew install skeptomai/tap/pelagos-mac
#   pelagos ping
#
# The production formula in skeptomai/homebrew-tap is identical except the
# urls are https://github.com/…/releases/download/… instead of file://.
#
# Prerequisites: out/ must exist (run scripts/build-vm-image.sh first).

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO/out"
DIST="$REPO/dist"
TAP_DIR="$DIST/tap"

# ---------------------------------------------------------------------------
# Version
# ---------------------------------------------------------------------------
VERSION="$(grep '^version\s*=' "$REPO/Cargo.toml" | head -1 | sed 's/.*"\(.*\)".*/\1/')"
BIN_TARBALL="pelagos-mac-${VERSION}-aarch64-apple-darwin.tar.gz"
VM_TARBALL="pelagos-mac-vm-${VERSION}.tar.gz"

echo "[release] version ${VERSION}"

# ---------------------------------------------------------------------------
# Check prerequisites
# ---------------------------------------------------------------------------
for f in ubuntu-vmlinuz initramfs-custom.gz root.img; do
    if [[ ! -f "$OUT/$f" ]]; then
        echo "ERROR: $OUT/$f not found"
        echo "       Run scripts/build-vm-image.sh first."
        exit 1
    fi
done

# ---------------------------------------------------------------------------
# Build + sign
# ---------------------------------------------------------------------------
echo "[release] building pelagos..."
cargo build -p pelagos-mac --release 2>&1 | grep -E "Compiling|Finished|^error"

echo "[release] building pelagos-docker..."
cargo build -p pelagos-docker --release 2>&1 | grep -E "Compiling|Finished|^error"

echo "[release] signing pelagos..."
bash "$REPO/scripts/sign.sh"

# ---------------------------------------------------------------------------
# Pack binary tarball
# ---------------------------------------------------------------------------
mkdir -p "$DIST"
BIN_STAGING="$(mktemp -d)"
VM_STAGING="$(mktemp -d)"
trap 'rm -rf "$BIN_STAGING" "$VM_STAGING"' EXIT

cp "$REPO/target/aarch64-apple-darwin/release/pelagos"        "$BIN_STAGING/pelagos"
cp "$REPO/target/aarch64-apple-darwin/release/pelagos-docker" "$BIN_STAGING/pelagos-docker"

echo "[release] packing ${BIN_TARBALL}..."
COPYFILE_DISABLE=1 tar -czf "$DIST/$BIN_TARBALL" -C "$BIN_STAGING" .
BIN_SHA256="$(shasum -a 256 "$DIST/$BIN_TARBALL" | awk '{print $1}')"
BIN_SIZE="$(du -sh "$DIST/$BIN_TARBALL" | awk '{print $1}')"
echo "[release]   ${BIN_TARBALL}  (${BIN_SIZE})  sha256: ${BIN_SHA256}"

# ---------------------------------------------------------------------------
# Pack VM tarball
# ---------------------------------------------------------------------------
# Normalise names: drop ubuntu- prefix and -custom suffix so auto-discovery
# finds them under the generic names (vmlinuz, initramfs.gz).
cp "$OUT/ubuntu-vmlinuz"      "$VM_STAGING/vmlinuz"
cp "$OUT/initramfs-custom.gz" "$VM_STAGING/initramfs.gz"
cp "$OUT/root.img"            "$VM_STAGING/root.img"

echo "[release] packing ${VM_TARBALL}..."
# root.img is a sparse ext4 image (~8.6 GiB logical, ~126 MiB actual data).
# COPYFILE_DISABLE suppresses macOS ._resource-fork sidecars; zeros in the
# sparse regions compress to near-nothing under gzip.
COPYFILE_DISABLE=1 tar -czf "$DIST/$VM_TARBALL" -C "$VM_STAGING" .
VM_SHA256="$(shasum -a 256 "$DIST/$VM_TARBALL" | awk '{print $1}')"
VM_SIZE="$(du -sh "$DIST/$VM_TARBALL" | awk '{print $1}')"
echo "[release]   ${VM_TARBALL}  (${VM_SIZE})  sha256: ${VM_SHA256}"

# ---------------------------------------------------------------------------
# Write formula into the local tap directory
# ---------------------------------------------------------------------------
# Homebrew 4.x+ requires formulas to be in a tap (a git repo).
# dist/tap/ is that local tap, registered as skeptomai/tap.
mkdir -p "$TAP_DIR/Formula"

BIN_URL="file://${DIST}/${BIN_TARBALL}"
VM_URL="file://${DIST}/${VM_TARBALL}"

cat > "$TAP_DIR/Formula/pelagos-mac.rb" <<FORMULA
# pelagos-mac Homebrew formula — LOCAL TEST BUILD
#
# Generated by scripts/build-release.sh.  Do not commit this file to the
# main repo; the canonical formula lives in skeptomai/homebrew-tap.
# The production formula is identical except urls are https://github.com/…
#
# Install:   brew install skeptomai/tap/pelagos-mac
# Uninstall: brew uninstall pelagos-mac && brew untap skeptomai/tap

class PelagosMac < Formula
  desc "Linux container runtime for Apple Silicon via Virtualization.framework"
  homepage "https://github.com/skeptomai/pelagos-mac"
  version "${VERSION}"

  url "${BIN_URL}"
  sha256 "${BIN_SHA256}"

  resource "vm" do
    url "${VM_URL}"
    sha256 "${VM_SHA256}"
  end

  def install
    bin.install "pelagos"
    bin.install "pelagos-docker"
    resource("vm").stage { (share/"pelagos-mac").install Dir["*"] }
  end

  test do
    assert_match "pelagos", shell_output("#{bin}/pelagos --help 2>&1")
  end
end
FORMULA

# ---------------------------------------------------------------------------
# Register / refresh the local tap
# ---------------------------------------------------------------------------
# Homebrew requires the tap directory to be a git repo.
if [[ ! -d "$TAP_DIR/.git" ]]; then
    git -C "$TAP_DIR" init -q
    git -C "$TAP_DIR" add Formula/pelagos-mac.rb
    git -C "$TAP_DIR" -c user.email="local" -c user.name="local" \
        commit -q -m "init"
else
    git -C "$TAP_DIR" add Formula/pelagos-mac.rb
    git -C "$TAP_DIR" -c user.email="local" -c user.name="local" \
        commit -q -m "update formula v${VERSION}" 2>/dev/null || true
fi

# Tap it (or re-tap if the path changed).
if brew tap | grep -q "^skeptomai/tap$"; then
    brew untap skeptomai/tap
fi
brew tap skeptomai/tap "$TAP_DIR" --quiet

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "[release] done."
echo ""
echo "  Tarballs:"
echo "    $DIST/$BIN_TARBALL"
echo "    $DIST/$VM_TARBALL"
echo ""
echo "  To install:"
echo "    brew install skeptomai/tap/pelagos-mac"
echo ""
echo "  To verify:"
echo "    pelagos ping"
echo ""
echo "  To uninstall:"
echo "    brew uninstall pelagos-mac && brew untap skeptomai/tap"
